version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: ${MYSQL_DB}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  mysql_data:
